#!/usr/bin/env sh

# initialization
arch -arm64e sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="arch -arm64e sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      2000.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  00
yabai -m config bottom_padding               00
yabai -m config left_padding                 00
yabai -m config right_padding                00
yabai -m config window_gap                   6

# animation
yabai -m config window_animation_duration    0.30

# rules
# otherApp='^(IINA|访达|Calendar|日历|System Preferences|系统偏好设置|Mail|WeChatc|QQ|印象笔记|灵犀|网易云音乐|Tencent Lemon|企业微信|Todoist|Input Source Pro|Enpass|预览|scrcpy|文本编辑|Kap|Shottr)$'
# yabai -m rule --add app="${otherApp}" manage=off

## specific rule
# yabai -m rule --add app="^IntelliJ IDEA$" manage=off
# yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on

yabai -m rule --add app="^iStat*" sticky=on layer=above manage=off border=off
yabai -m rule --add app="^System Preferences*" manage=off

echo "yabai configuration loaded.."
